name: Update media index

on:
  push:
    branches: [ main ]
    paths:
      - 'v2.0/media/**'
      - 'v2.0/tools/gen_media_index.mjs'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'
      - name: Generate media index
        run: node v2.0/tools/gen_media_index.mjs
      - name: Commit updated index.json (if changed)
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore(media): update index.json via CI"
          file_pattern: v2.0/media/index.json
